### ISSUE TITLE
Flash in button

### ISSUE THREAD

**Issue by bl1nder** [iwiznia/Ext.ux.Exporter#4]
Why you use a flash-button in code? it 's need only for beaty?Can  use  it with standard Extjs button? thanks

**Comment by iwiznia** [comment]
It's because the other way of downloading a file directly within the browser is encoding the content in a link, and that has a pretty low limit of data it can handle before crashing a browser... with the flash solution there's no limit in the size of the generated file, that's why downloadify is used.
